"""Description of changes

Revision ID: 890de7ccf6b9
Revises: f9bae8021d25
Create Date: 2024-08-01 18:58:02.592744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890de7ccf6b9'
down_revision = 'f9bae8021d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('activity_types', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('physical_levels', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('limitations', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('primary_goals', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('available_time', sa.String(), nullable=True))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('available_time')
        batch_op.drop_column('budget')
        batch_op.drop_column('primary_goals')
        batch_op.drop_column('limitations')
        batch_op.drop_column('physical_levels')
        batch_op.drop_column('activity_types')
        batch_op.drop_column('interests')
        batch_op.drop_column('location')
        batch_op.drop_column('age')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
