"""empty message

Revision ID: 9b3b070dcae9
Revises: b0809985e7e3
Create Date: 2024-09-17 15:08:51.697561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3b070dcae9'
down_revision = 'b0809985e7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_tags', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('liked_tags')

    # ### end Alembic commands ###
