"""Add Tags field to Activity model

Revision ID: b0809985e7e3
Revises: 890de7ccf6b9
Create Date: 2024-09-16 17:00:21.969408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0809985e7e3'
down_revision = '890de7ccf6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
