"""links are made non nullabe

Revision ID: f9bae8021d25
Revises: ed410024e88b
Create Date: 2024-07-23 14:47:23.942676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bae8021d25'
down_revision = 'ed410024e88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('youtube_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('meetup_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('google_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('google_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('meetup_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('youtube_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
